baseurl: "/bulmaswatch" # the subpath of your site, e.g. /blog
url: "https://jenil.github.io" # the base hostname & protocol for your site, e.g. http://example.com

title: Bulmaswatch
email: i@jgog.in
description: Free themes for Bulma - A modern CSS framework based on Flexbox
twitter_username: geekGogari
github_username:  jenil
repo_url: //github.com/jenil/bulmaswatch
collections:
 themes:
    output: true
    permalink: /:name/
defaults:
  - scope:
      path: ""
      type: themes
    values:
      layout: theme
      order: 1
# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
